# This is a basic workflow to help you get started with Actions

name: ReadyAPI Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    RAPI_PROJECT_PATH: ${{ github.workspace }}

jobs:
  Run-Tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - uses: actions/checkout@v1
      
      - name: Download ReadyAPI
        run: curl https://dl.eviware.com/ready-api/3.40.1.0/ReadyAPI-x64-3.40.1.sh -o ~/ReadyAPI-x64-3.40.1.exe
        
      - name: Install ReadyAPI
        run: ./ReadyAPI-x64-3.53.0.sh -c

      - name: Run ReadyAPI Tests
        # navigate to the ReadyAPI Installation bin folder
        working-directory: C:\Program Files\SmartBear\ReadyAPI-3.40.1\bin\
      
        # execute the ReadyAPI project stored in repository
        run: cmd /c "testrunner.bat -r -a -j -f${WORKSPACE} "-RJUnit-Style HTML Report" -FXML -accessKey "9db1afca-70a8-40f4-9611-317f7d3b689f" "-EDefault environment" ${{ env.RAPI_PROJECT_PATH }}"
