# This is a basic workflow to help you get started with Actions

name: ReadyAPI Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run-Tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - uses: actions/checkout@v1

     # - name: create downloads folder
      #  run: |
       #  mkdir -p ~/Downloads
         
      
      - name: Download ReadyAPI installer
        run: curl https://dl.eviware.com/ready-api/3.40.1.0/ReadyAPI-x64-3.40.1.sh -o ~/Downloads/ReadyAPI-x64-3.40.1.sh

      - name: List directory contents recursively on Ubuntu
        run: |
         ls -la ~/Downloads

    #  run: echo ReadyAPI Downloaded Successfully

      - name: Make installer executable
        run: chmod +x ~/Downloads/ReadyAPI-x64-3.40.1.sh

      - name: Check if shell script is executable
        run: |

         DIRECTORY_PATH="~/Downloads"

         if [ -x "$DIRECTORY_PATH" ]; then
          echo "Directory $DIRECTORY_PATH exists."
          else
            echo "Directory $DIRECTORY_PATH does not exist."
            exit 1
          fi

      - name: Install ReadyAPI
        run: ./Downloads/ReadyAPI-x64-3.40.1.sh -c
    
        # execute the ReadyAPI project stored in repository
        #run: cmd /c "testrunner.bat -r -a -j -f${WORKSPACE} "-RJUnit-Style HTML Report" -FXML -accessKey "9db1afca-70a8-40f4-9611-317f7d3b689f" "-EDefault environment" ${{ env.RAPI_PROJECT_PATH }}"
